### ISSUE TITLE
其他操作系统如windows也有进程之间的家族关系

### ISSUE THREAD

**Issue by everything411** [songshangru/BIT-CS-Learning#1]
https://github.com/songshangru/BIT-CS-Learning/blob/8e3a0697d974d5bc286607624a6a140871404058/os/os%E6%8F%90%E7%BA%B2(ssr)/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F.md#L143

树形结构的进程结构的系统都会记录

**Comment by songshangru** [comment]
这里是我的疏漏，ppt上原话是windows进程不具备父子关系

**Comment by songshangru** [comment]
windows进程具有较弱的父子联系，可查阅EPROCESS结构做进一步了解
